version: '3.8'
services:
  auth_service:
    build: ./blog_auth
    command: flask run --host=0.0.0.0
    volumes:
      - ./auth_service:/app

  blog_service:
    build: ./blog_posts
    command: flask run --host=0.0.0.0
    volumes:
      - ./auth_service:/app

  metrics_service:
    build: ./blog_metrics
    command: flask run --host=0.0.0.0
    volumes:
      - ./auth_service:/app
